CREATE TABLE "Crafts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" text,
    CONSTRAINT "PK_Crafts" PRIMARY KEY ("Id")
);


CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Email" character varying(254) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);


CREATE TABLE "Craftsmen" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "ContactInfo" text,
    "DailyRate" numeric(18,2) NOT NULL,
    "Status" text NOT NULL,
    "LastCheckedAt" timestamp without time zone,
    CONSTRAINT "PK_Craftsmen" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Craftsmen_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Customers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "ContactInfo" text,
    "LastCheckedAt" timestamp without time zone,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Customers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "CraftsmanCrafts" (
    "CraftsmanId" integer NOT NULL,
    "CraftId" integer NOT NULL,
    CONSTRAINT "PK_CraftsmanCrafts" PRIMARY KEY ("CraftsmanId", "CraftId"),
    CONSTRAINT "FK_CraftsmanCrafts_Crafts_CraftId" FOREIGN KEY ("CraftId") REFERENCES "Crafts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CraftsmanCrafts_Craftsmen_CraftsmanId" FOREIGN KEY ("CraftsmanId") REFERENCES "Craftsmen" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Requests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer NOT NULL,
    "CraftsmanId" integer NOT NULL,
    "CraftId" integer NOT NULL,
    "NeededOn" timestamp without time zone NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "Description" text NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "RespondedAt" timestamp without time zone,
    CONSTRAINT "PK_Requests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Requests_Crafts_CraftId" FOREIGN KEY ("CraftId") REFERENCES "Crafts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Requests_Craftsmen_CraftsmanId" FOREIGN KEY ("CraftsmanId") REFERENCES "Craftsmen" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Requests_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE
);


CREATE UNIQUE INDEX "IX_Crafts_Name" ON "Crafts" ("Name");


CREATE INDEX "IX_CraftsmanCrafts_CraftId" ON "CraftsmanCrafts" ("CraftId");


CREATE UNIQUE INDEX "IX_Craftsmen_UserId" ON "Craftsmen" ("UserId");


CREATE UNIQUE INDEX "IX_Customers_UserId" ON "Customers" ("UserId");


CREATE INDEX "IX_Requests_CraftId" ON "Requests" ("CraftId");


CREATE UNIQUE INDEX "IX_Requests_CraftsmanId_NeededOn" ON "Requests" ("CraftsmanId", "NeededOn") WHERE "Status" = 'Accepted';


CREATE INDEX "IX_Requests_CustomerId" ON "Requests" ("CustomerId");


CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");


alter table "Users" enable row level security;
alter table "Craftsmen" enable row level security;
alter table "Crafts" enable row level security;
alter table "CraftsmanCrafts" enable row level security;
alter table "Customers" enable row level security;
alter table "Requests" enable row level security;
